# Generated by Django 5.1.15 on 2026-01-20 23:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gerencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nombre de Gerencia"
                    ),
                ),
                ("descripcion", models.TextField(blank=True, verbose_name="Descripción")),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gerencia",
                "verbose_name_plural": "Gerencias",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre de Área")),
                ("descripcion", models.TextField(blank=True, verbose_name="Descripción")),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "gerencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="personal.gerencia",
                        verbose_name="Gerencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "ordering": ["gerencia", "nombre"],
                "unique_together": {("nombre", "gerencia")},
            },
        ),
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo_doc",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("CE", "Carné de Extranjería"),
                            ("Pasaporte", "Pasaporte"),
                        ],
                        default="DNI",
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "nro_doc",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Documento"
                    ),
                ),
                (
                    "apellidos_nombres",
                    models.CharField(max_length=250, verbose_name="Apellidos y Nombres"),
                ),
                (
                    "codigo_fotocheck",
                    models.CharField(
                        blank=True,
                        help_text="Código de barras del fotocheck",
                        max_length=30,
                        verbose_name="Código Fotocheck",
                    ),
                ),
                ("cargo", models.CharField(max_length=150, verbose_name="Cargo")),
                (
                    "tipo_trab",
                    models.CharField(
                        choices=[("Empleado", "Empleado"), ("Obrero", "Obrero")],
                        max_length=20,
                        verbose_name="Tipo de Trabajador",
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Alta"),
                ),
                (
                    "fecha_cese",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Cese"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Activo", "Activo"),
                            ("Inactivo", "Inactivo"),
                            ("Suspendido", "Suspendido"),
                            ("Cesado", "Cesado"),
                        ],
                        default="Activo",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Nacimiento"),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                ("celular", models.CharField(blank=True, max_length=20, verbose_name="Celular")),
                (
                    "correo_personal",
                    models.EmailField(blank=True, max_length=254, verbose_name="Correo Personal"),
                ),
                (
                    "correo_corporativo",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo Corporativo"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(blank=True, max_length=300, verbose_name="Dirección"),
                ),
                ("ubigeo", models.CharField(blank=True, max_length=100, verbose_name="Ubigeo")),
                (
                    "afp",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Habitat", "Habitat"),
                            ("Integra", "Integra"),
                            ("Prima", "Prima"),
                            ("Profuturo", "Profuturo"),
                        ],
                        max_length=20,
                        verbose_name="AFP",
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BCP", "BCP"),
                            ("BBVA", "BBVA"),
                            ("Scotiabank", "Scotiabank"),
                            ("Interbank", "Interbank"),
                            ("Banco de la Nación", "Banco de la Nación"),
                            ("Falabella", "Falabella"),
                        ],
                        max_length=30,
                        verbose_name="Banco",
                    ),
                ),
                (
                    "cuenta_ahorros",
                    models.CharField(blank=True, max_length=50, verbose_name="Cuenta de Ahorros"),
                ),
                (
                    "cuenta_cci",
                    models.CharField(blank=True, max_length=50, verbose_name="Cuenta CCI"),
                ),
                (
                    "cuenta_cts",
                    models.CharField(blank=True, max_length=50, verbose_name="Cuenta CTS"),
                ),
                (
                    "sueldo_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Sueldo Base",
                    ),
                ),
                (
                    "bonos",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Bonos",
                    ),
                ),
                (
                    "regimen_laboral",
                    models.CharField(blank=True, max_length=50, verbose_name="Régimen Laboral"),
                ),
                (
                    "regimen_turno",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 14x7, 21x7, etc.",
                        max_length=30,
                        verbose_name="Régimen de Turno",
                    ),
                ),
                ("observaciones", models.TextField(blank=True, verbose_name="Observaciones")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_asignado",
                        to="personal.area",
                        verbose_name="Área Asignada",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        help_text="Cuenta de acceso si aplica",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_data",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario del Sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal",
                "verbose_name_plural": "Personal",
                "ordering": ["apellidos_nombres"],
            },
        ),
        migrations.AddField(
            model_name="gerencia",
            name="responsable",
            field=models.OneToOneField(
                blank=True,
                help_text="Persona responsable de esta gerencia",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gerencia_responsable",
                to="personal.personal",
                verbose_name="Responsable",
            ),
        ),
        migrations.CreateModel(
            name="Roster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text="Código del turno asignado",
                        max_length=100,
                        verbose_name="Código de Turno",
                    ),
                ),
                (
                    "dias_libres_ganados",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Acumulado histórico de días libres antes del corte",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Días Libres Ganados",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=300, verbose_name="Observaciones"),
                ),
                (
                    "fuente",
                    models.CharField(
                        blank=True,
                        help_text="Origen del registro (archivo, usuario, etc.)",
                        max_length=200,
                        verbose_name="Fuente",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_dias",
                        to="personal.personal",
                        verbose_name="Personal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roster",
                "verbose_name_plural": "Roster",
                "ordering": ["fecha", "personal"],
            },
        ),
        migrations.CreateModel(
            name="RosterAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha del Registro")),
                (
                    "campo_modificado",
                    models.CharField(
                        help_text="Nombre del campo que fue modificado",
                        max_length=50,
                        verbose_name="Campo Modificado",
                    ),
                ),
                ("valor_anterior", models.TextField(blank=True, verbose_name="Valor Anterior")),
                ("valor_nuevo", models.TextField(blank=True, verbose_name="Valor Nuevo")),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Auditoría"),
                ),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_audits",
                        to="personal.personal",
                        verbose_name="Personal",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que realizó el cambio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría de Roster",
                "verbose_name_plural": "Auditorías de Roster",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AddIndex(
            model_name="personal",
            index=models.Index(fields=["nro_doc"], name="personal_pe_nro_doc_079b86_idx"),
        ),
        migrations.AddIndex(
            model_name="personal",
            index=models.Index(fields=["estado"], name="personal_pe_estado_e712bc_idx"),
        ),
        migrations.AddIndex(
            model_name="personal",
            index=models.Index(fields=["area"], name="personal_pe_area_id_fbf703_idx"),
        ),
        migrations.AddIndex(
            model_name="roster",
            index=models.Index(fields=["personal", "fecha"], name="personal_ro_persona_67262c_idx"),
        ),
        migrations.AddIndex(
            model_name="roster",
            index=models.Index(fields=["fecha"], name="personal_ro_fecha_6e82a0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="roster",
            unique_together={("personal", "fecha")},
        ),
        migrations.AddIndex(
            model_name="rosteraudit",
            index=models.Index(fields=["personal", "fecha"], name="personal_ro_persona_ba546c_idx"),
        ),
        migrations.AddIndex(
            model_name="rosteraudit",
            index=models.Index(fields=["-creado_en"], name="personal_ro_creado__585704_idx"),
        ),
    ]
