# Generated by Django 5.1.15 on 2026-01-20 23:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="dias_libres_ganados",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Acumulado de días libres antes del corte",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="Días Libres Ganados",
            ),
        ),
    ]
