# Generated by Django 5.1.15 on 2026-01-20 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0002_personal_dias_libres_ganados"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roster",
            name="dias_libres_ganados",
        ),
    ]
