# Generated by Django 5.1.15 on 2026-01-21 03:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0003_remove_roster_dias_libres_ganados"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personal",
            name="dias_libres_ganados",
        ),
        migrations.AddField(
            model_name="personal",
            name="dias_libres_corte_2025",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Días libres acumulados al corte del 31 de diciembre de 2025 (valor manual)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="Días Libres al 31/12/25",
            ),
        ),
    ]
