# Generated by Django 5.1.15 on 2026-01-22 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0005_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="roster",
            name="aprobado_en",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fecha de Aprobación"),
        ),
        migrations.AddField(
            model_name="roster",
            name="aprobado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roster_aprobaciones",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprobado por",
            ),
        ),
        migrations.AddField(
            model_name="roster",
            name="estado",
            field=models.CharField(
                choices=[
                    ("aprobado", "Aprobado"),
                    ("pendiente", "Pendiente de Aprobación"),
                    ("borrador", "Borrador"),
                ],
                default="aprobado",
                help_text="Estado del registro: borrador, pendiente o aprobado",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AddField(
            model_name="roster",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roster_modificaciones",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
        ),
        migrations.AddIndex(
            model_name="roster",
            index=models.Index(fields=["estado"], name="personal_ro_estado_f862ba_idx"),
        ),
    ]
