# Generated by Django 5.1.15 on 2026-01-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0006_roster_aprobado_en_roster_aprobado_por_roster_estado_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["gerencia", "activa"], name="personal_ar_gerenci_069b9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["nombre"], name="personal_ar_nombre_c5a5bd_idx"),
        ),
        migrations.AddIndex(
            model_name="gerencia",
            index=models.Index(fields=["nombre"], name="personal_ge_nombre_befee9_idx"),
        ),
        migrations.AddIndex(
            model_name="gerencia",
            index=models.Index(fields=["activa"], name="personal_ge_activa_c15cd9_idx"),
        ),
    ]
