# Generated by Django 5.1.15 on 2026-01-22 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0007_area_personal_ar_gerenci_069b9f_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre de SubÁrea")),
                ("descripcion", models.TextField(blank=True, verbose_name="Descripción")),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SubÁrea",
                "verbose_name_plural": "SubÁreas",
                "ordering": ["area", "nombre"],
            },
        ),
        migrations.RemoveField(
            model_name="gerencia",
            name="responsable",
        ),
        migrations.AlterModelOptions(
            name="area",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
            },
        ),
        migrations.RemoveIndex(
            model_name="area",
            name="personal_ar_gerenci_069b9f_idx",
        ),
        migrations.RemoveIndex(
            model_name="personal",
            name="personal_pe_area_id_fbf703_idx",
        ),
        migrations.AlterUniqueTogether(
            name="area",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="personal",
            name="area",
        ),
        migrations.AddField(
            model_name="area",
            name="responsable",
            field=models.OneToOneField(
                blank=True,
                help_text="Persona responsable de esta área",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="area_responsable",
                to="personal.personal",
                verbose_name="Responsable",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="nombre",
            field=models.CharField(max_length=150, unique=True, verbose_name="Nombre de Área"),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["activa"], name="personal_ar_activa_682562_idx"),
        ),
        migrations.AddField(
            model_name="subarea",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subareas",
                to="personal.area",
                verbose_name="Área",
            ),
        ),
        migrations.AddField(
            model_name="personal",
            name="subarea",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personal_asignado",
                to="personal.subarea",
                verbose_name="SubÁrea Asignada",
            ),
        ),
        migrations.AddIndex(
            model_name="personal",
            index=models.Index(fields=["subarea"], name="personal_pe_subarea_98dcf5_idx"),
        ),
        migrations.RemoveField(
            model_name="area",
            name="gerencia",
        ),
        migrations.AddIndex(
            model_name="subarea",
            index=models.Index(fields=["area", "activa"], name="personal_su_area_id_7c8b46_idx"),
        ),
        migrations.AddIndex(
            model_name="subarea",
            index=models.Index(fields=["nombre"], name="personal_su_nombre_f164ba_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="subarea",
            unique_together={("nombre", "area")},
        ),
        migrations.DeleteModel(
            name="Gerencia",
        ),
    ]
