# Generated by Django 5.1.15 on 2026-02-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0009_area_responsables_m2m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="responsables",
            field=models.ManyToManyField(
                blank=True,
                help_text="Personas responsables de esta área",
                related_name="areas_responsable",
                to="personal.personal",
                verbose_name="Responsables",
            ),
        ),
    ]
